"""
Atelier Academic Search Module.

This module houses the AtelierAcademicSearch engine, which orchestrates 
queries across local vector databases and external APIs (PubMed, Europe PMC, 
OpenAlex, Semantic Scholar).
"""

import logging
import xml.etree.ElementTree as ET
from typing import Dict, List, Any

from database.models import Record
from core.config import OPENALEX_API_KEY, SEMANTIC_SCHOLAR_API_KEY
from .paper import PubMedEngine, EuropePMCEngine, OpenAlexEngine, SemanticScholarEngine
from .http_client import HttpClient

logger = logging.getLogger(__name__)


class AtelierAcademicSearch:
    """
    The unified search manager called by the Orchestrator.
    
    Routes AI-generated boolean queries to the precise OOP engines and
    seamlessly maps their distinct outputs back to the application's core 
    Database Record model.
    """

    def __init__(self, db_repository: Any = None, max_results_per_source: int = 20):
        """
        Initializes the comprehensive search manager.

        Args:
            db_repository (Any, optional): The database repository for local vector search. Defaults to None.
            max_results_per_source (int, optional): The limit of papers to retrieve per engine. Defaults to 20.
        """
        self.db_repo = db_repository
        self.max_results = max_results_per_source

        pubmed_client = HttpClient(timeout=25, request_per_second=2.5)
        epmc_client = HttpClient(timeout=25, request_per_second=4.0)
        openalex_client = HttpClient(timeout=25, request_per_second=4.0)
        s2_client = HttpClient(timeout=25, request_per_second=2.0)
        
        # Initialize the OOP API engines with their respective keys
        self.engines = {
            "pubmed": PubMedEngine(client=pubmed_client),
            "europe_pmc": EuropePMCEngine(client=epmc_client),
            "openalex": OpenAlexEngine(api_key=OPENALEX_API_KEY, client=openalex_client),
            "semantic_scholar": SemanticScholarEngine(api_key=SEMANTIC_SCHOLAR_API_KEY, client=s2_client)
        }

    def _convert_to_db_record(self, paper: Any) -> Record:
        """
        Converts an engine-specific PaperRecord into the standard Database Record.

        Args:
            paper (Any): The PaperRecord object returned by a specific engine.

        Returns:
            Record: The standardized application database record.
        """
        return Record(
            source=paper.source,
            source_id=paper.source_id or "",
            all_sources=[paper.source],
            title=paper.title,
            abstract=paper.abstract or "",
            year=paper.year,
            journal=paper.journal or "",
            authors=paper.authors,
            doi=paper.doi or "",
            pmid=paper.pmid or "",
            pmcid=paper.pmcid or "",
            pdf_url=paper.pdf_url or "",
            full_text_url=paper.full_text_url or "",
            citation_count=paper.citation_count,
            fingerprint=paper.fingerprint
        )

    def fetch_full_text_from_epmc(self, pmcid: str) -> str:
        """
        Dedicated method for the Orchestrator to download XML full text from Europe PMC.

        Args:
            pmcid (str): The PubMed Central ID (e.g., 'PMC1234567').

        Returns:
            str: The parsed full text as a string, or an empty string if it fails.
        """
        if not pmcid: 
            return ""
            
        try:
            # Borrow the configured HTTP client from the Europe PMC engine
            target_url = f"https://www.ebi.ac.uk/europepmc/webservices/rest/{pmcid}/fullTextXML"
            xml_text = self.engines["europe_pmc"].client.get_text(target_url)
            
            if not xml_text: 
                return ""
                
            root = ET.fromstring(xml_text)
            return "\n\n".join(["".join(p.itertext()).strip() for p in root.findall(".//p") if "".join(p.itertext()).strip()])
            
        except Exception as e:
            logger.warning(f"Failed to fetch XML full text for {pmcid}: {e}")
            return ""

    def run_comprehensive_search(self, plan: Dict[str, str], current_topic: str) -> List[Record]:
        """
        Executes the search plan across the local DB and external APIs simultaneously.

        Args:
            plan (Dict[str, str]): The JSON boolean query plan generated by the LLM.
            current_topic (str): The user's original natural language topic.

        Returns:
            List[Record]: A deduplicated list of standardized Database Records.
        """
        results: List[Record] = []
        seen: set[str] = set()

        # 1. Fetch from Local Database first (Costs 0 API calls/tokens!)
        if self.db_repo:
            logger.info("Checking local database for previously stored vectors...")
            local_records = self.db_repo.search_papers_by_vector(current_topic)
            for rec in local_records:
                if rec.fingerprint not in seen:
                    seen.add(rec.fingerprint)
                    results.append(rec)

        # 2. Map AI Plan to the appropriate engines
        query_map = {
            "pubmed": plan.get("pubmed_query"),
            "europe_pmc": plan.get("europe_pmc_query"),
            "openalex": plan.get("openalex_query"),
            "semantic_scholar": plan.get("semantic_scholar_query")
        }

        # 3. Execute external API engines
        logger.info("Executing external academic engine searches...")
        for engine_name, query in query_map.items():
            if not query or query.lower() == "null":
                continue
                
            engine = self.engines.get(engine_name)
            if engine:
                try:
                    logger.info(f"Querying {engine_name.upper()}...")
                    raw_papers = engine.search(query, limit=self.max_results)
                    
                    added_count = 0
                    for paper in raw_papers:
                        if paper.fingerprint not in seen:
                            seen.add(paper.fingerprint)
                            results.append(self._convert_to_db_record(paper))
                            added_count += 1
                            
                    logger.info(f"{engine_name.upper()} returned {added_count} new unique records.")
                    
                except Exception as e:
                    logger.error(f"{engine_name.upper()} fetch failed: {e}")

        logger.info(f"Comprehensive search completed. Total unique records: {len(results)}")
        return results