"""
Atelier AI Engine Module

This module houses the core Artificial Intelligence orchestrator for the application.
It uses the Factory Pattern to dynamically instantiate LangChain models on the fly
with task-specific temperatures, ensuring strictness for data extraction and 
creativity for synthesis and chat.
"""

import re
import json
import logging
import warnings
from typing import Dict, List, Any

from langchain_core.language_models import BaseChatModel
from langchain_core.messages import SystemMessage, HumanMessage, AIMessage
from langchain_core.output_parsers import StrOutputParser
from langchain_core.prompts import ChatPromptTemplate
from tenacity import retry, stop_after_attempt, wait_exponential

from core.config import (
    ANTHROPIC_API_KEY,
    GOOGLE_API_KEY,
    GROQ_API_KEY,
    OPENAI_API_KEY
)
from core.exceptions import AIOutputError, AIProviderError, AtelierAIError
from llm.utils import _common_llm_params, resolve_model_config, get_model_choices

warnings.filterwarnings("ignore")
logger = logging.getLogger(__name__)

# ==========================================
# 1. STANDALONE HELPERS
# ==========================================

def _get_val(obj: Any, key: str, default: Any = "") -> Any:
    """
    Safely extracts a value from an object, accommodating both Dictionary 
    formats (from SQLite) and Class Instances (from live requests).
    
    Args:
        obj (Any): The object to inspect.
        key (str): The attribute or dictionary key to retrieve.
        default (Any): The fallback value if the key does not exist.
        
    Returns:
        Any: The extracted value or the default.
    """
    if isinstance(obj, dict):
        return obj.get(key, default)
    return getattr(obj, key, default)


def _enrich_citations(text: str, records: List[Any]) -> str:
    """
    Finds academic citations like [1] or [2] in text and converts them into 
    interactive Tailwind CSS bubbles with hover tooltips displaying author and title.
    
    Args:
        text (str): The raw markdown generated by the AI.
        records (List[Any]): The list of papers serving as the context.
        
    Returns:
        str: HTML-enriched text ready for Dash rendering.
    """
    def replace_cite(match):
        idx = int(match.group(1)) - 1
        
        # Ensure the index is within the bounds of our context list
        if 0 <= idx < len(records):
            rec = records[idx]
            
            # Extract metadata safely
            title = _get_val(rec, 'title', 'Unknown Title')
            year = _get_val(rec, 'year', 'N.D.')
            authors = _get_val(rec, 'authors', [])
            author = authors[0] if authors else 'Unknown'
            
            # Build the interactive tooltip
            tooltip = (
                f"<div class='absolute bottom-full left-1/2 -translate-x-1/2 mb-2 hidden group-hover:block "
                f"w-64 p-3 bg-slate-800 text-white text-xs rounded-xl shadow-xl z-50 pointer-events-none'>"
                f"<strong>{author} ({year})</strong><br/>{title}</div>"
            )
            
            # Build the interactive bubble
            return (
                f'<span class="relative group cursor-help inline-flex items-center justify-center '
                f'w-5 h-5 rounded-full bg-secondary-container text-on-secondary-container '
                f'text-[10px] font-bold mx-0.5">{idx+1}{tooltip}</span>'
            )
            
        return match.group(0) # Return unchanged if index is invalid
    
    return re.sub(r'\[(\d+)\]', replace_cite, text)


def parse_llm_json(raw_text: str) -> dict:
    """
    Aggressively cleans LLM output to extract JSON, stripping markdown formatting 
    and model "thinking" tags (e.g., DeepSeek's <think> tags).
    
    Args:
        raw_text (str): The raw string output from the LLM.
        
    Returns:
        dict: The parsed Python dictionary.
        
    Raises:
        AIOutputError: If no valid JSON structure can be found in the text.
    """
    # 1. Strip reasoning blocks
    cleaned = re.sub(r"<think>.*?</think>", " ", raw_text, flags=re.DOTALL | re.IGNORECASE).strip()
    
    # 2. Strip markdown code fences
    if cleaned.startswith("```"):
        cleaned = re.sub(r"^```[a-zA-Z0-9_-]*\n", "", cleaned)
        cleaned = re.sub(r"\n```$", "", cleaned).strip()
    
    # 3. Locate JSON boundaries
    start = cleaned.find('{')
    end = cleaned.rfind('}') + 1
    
    if start != -1 and end != -1:
        try: 
            return json.loads(cleaned[start:end])
        except Exception: 
            pass
            
    raise AIOutputError(f"LLM Output could not be parsed as JSON: {raw_text[:100]}...")


# ==========================================
# 2. THE AI ENGINE CLASS
# ==========================================

class AtelierAIEngine:
    """
    The central intelligence orchestrator for Atelier.
    
    This class manages all interactions with external LLM providers (OpenAI, 
    Anthropic, Groq, Google). It should be instantiated per-request within 
    Dash callbacks to ensure stateless, dynamic execution.
    """

    def __init__(self, model_choice: str):
        """
        Stores the user's requested model and validates its existence.
        
        Args:
            model_choice (str): The string identifier for the model (e.g., 'gpt-4o').
            
        Raises:
            ValueError: If the requested model is not found in the configuration.
        """
        self.model_choice = model_choice
        
        # Validate that the model exists in the configuration
        if not resolve_model_config(model_choice):
            supported = ", ".join(get_model_choices())
            raise ValueError(f"Unsupported model '{model_choice}'. Supported: {supported}")

    def _get_llm(self, temperature: float = 0.0) -> BaseChatModel:
        """
        Internal Factory: Instantiates the chosen LangChain model at the required temperature.
        
        Args:
            temperature (float): Creativity dial (0.0 for strict logic, 0.3+ for chat).
            
        Returns:
            BaseChatModel: An instantiated LangChain chat model ready for invocation.
        """
        config = resolve_model_config(self.model_choice)
        llm_class = config['class']
        model_specific_params = config.get('constructor_params', {})
        
        # Merge unified parameters with the specific requested temperature
        all_params = {**_common_llm_params, **model_specific_params, "temperature": temperature}
        
        # Verify environment keys before returning
        self._ensure_credentials(llm_class)
        
        return llm_class(**all_params)

    def _ensure_credentials(self, llm_class: Any) -> None:
        """
        Validates that the required environment variables are present for the chosen LLM provider.
        
        Args:
            llm_class (Any): The LangChain class reference for the requested model.
            
        Raises:
            ValueError: If the API key is missing for the target provider.
        """
        class_name = getattr(llm_class, "__name__", str(llm_class))
        
        if "ChatAnthropic" in class_name and not ANTHROPIC_API_KEY:
            raise ValueError(f"Anthropic model '{self.model_choice}' selected but ANTHROPIC_API_KEY is missing.")
        elif "ChatGoogleGenerativeAI" in class_name and not GOOGLE_API_KEY:
            raise ValueError(f"Google model '{self.model_choice}' selected but GOOGLE_API_KEY is missing.")
        elif "ChatGroq" in class_name and not GROQ_API_KEY:
            raise ValueError(f"Groq model '{self.model_choice}' selected but GROQ_API_KEY is missing.")
        elif "ChatOpenAI" in class_name and not OPENAI_API_KEY:
            raise ValueError(f"OpenAI model '{self.model_choice}' selected but OPENAI_API_KEY is missing.")

    @retry(stop=stop_after_attempt(3), wait=wait_exponential(multiplier=1, min=2, max=10), reraise=True)
    def _execute(self, temperature: float, system_msg: str, user_inputs: dict, is_json: bool = True) -> Any:
        """
        Internal unified execution wrapper featuring automatic exponential backoff retries.
        
        Args:
            temperature (float): The desired creativity setting for this specific call.
            system_msg (str): The system prompt defining the AI's persona and rules.
            user_inputs (dict): A dictionary containing the target payload mapping to `{input_data}`.
            is_json (bool): Whether the function should attempt to aggressively parse JSON output.
            
        Returns:
            Any: A Python dictionary (if is_json=True) or a raw string (if is_json=False).
            
        Raises:
            AIOutputError: If JSON extraction fails, triggering a Tenacity retry.
            AIProviderError: If the external API is unreachable or rate-limited.
        """
        llm = self._get_llm(temperature)
        
        prompt = ChatPromptTemplate.from_messages([
            ("system", system_msg),
            ("user", "{input_data}")
        ])
        
        chain = prompt | llm | StrOutputParser()
        
        try:
            response = chain.invoke(user_inputs)
            return parse_llm_json(response) if is_json else response
        except AIOutputError:
            raise  # Let Tenacity catch it and retry
        except Exception as e:
            raise AIProviderError(f"API Connection Error: {e}") from e

    # ==========================================
    # 3. PUBLIC API METHODS
    # ==========================================

    def plan_topic_queries(self, topic: str) -> dict:
        """
        Translates a natural language research topic into optimized boolean search strings.
        
        Args:
            topic (str): The user's natural language research question.
            
        Returns:
            dict: JSON object containing formatted queries for various databases.
        """
        sys_prompt = """
        You are an Expert Medical and Academic Literature Query Planner.
        Your task is to translate a user's natural language research topic into optimized search queries for academic databases (PubMed, Europe PMC, OpenAlex, Semantic Scholar).

        Rules:
        1. Extract the core scientific, medical, or sociological concepts.
        2. DO NOT let geographic terms overly restrict the search. If a specific country is mentioned (e.g., "Kenya"), you MUST broadly expand the geography (e.g., "Kenya" OR "East Africa" OR "LMIC" OR "Sub-Saharan Africa") to maximize recall.
        3. Remove stop words and unnecessary conversational phrasing.
        4. Output ONLY a valid JSON object.

        Output Schema:
        {{
        "pubmed_query": "<boolean string>",
        "europe_pmc_query": "<boolean string>",
        "openalex_query": "<clean keyword string>",
        "semantic_scholar_query": "<clean keyword string>"
        }}
        """
        try:
            return self._execute(temperature=0.0, system_msg=sys_prompt, user_inputs={"input_data": f"Topic: {topic}"})
        except AtelierAIError:
            logger.warning("Query planning failed. Falling back to keyword stripping.")
            cleaned = re.sub(r"[^\w\s]", "", topic)
            return {k: cleaned for k in ["pubmed_query", "europe_pmc_query", "openalex_query", "semantic_scholar_query"]}

    def extract_paper_data(self, topic: str, paper_json_str: str) -> dict:
        """
        Analyzes a single academic paper against the user's overarching research query.
        
        Args:
            topic (str): The user's overarching research question.
            paper_json_str (str): Stringified JSON representation of the paper's text.
            
        Returns:
            dict: Structured extraction data (e.g., 'is_relevant', 'population', 'results').
        """
        sys_prompt = """
        You are a rigorous Academic Data Extraction and Quality Control AI.
        Your task is to analyze a scientific paper's abstract (and full text, if provided) against a user's research query.

        Rules:
        1. Assess Relevance: Rate how directly this paper answers the user's query on a scale of 0 to 100. If it is entirely unrelated, set "is_relevant" to false.
        2. Extract Parameters: Identify the target population, study methodology, core results, measured outcomes, sample size (N), number of included studies (for meta-analyses), duration, and geographic location.
        3. If a parameter is not explicitly stated in the text, you MUST output "-". Do not guess.
        4. Provide a punchy, 1-sentence "answer" summarizing the paper's main takeaway regarding the user's query.
        5. Spin Check: If full text is provided, verify that the abstract does not exaggerate the findings.

        Output ONLY a valid JSON object matching this exact schema:
        {{
        "is_relevant": true,
        "ai_rank_score": 85,
        "answer": "<1-sentence direct answer>",
        "population": "<target demographic>",
        "methods": "<study design>",
        "results": "<main findings>",
        "outcomes": "<measured variables>",
        "sample_size": "<integer or '-'>",
        "study_count": "<integer or '-'>",
        "duration": "<timeframe or '-'>",
        "country": "<location or '-'>",
        "is_abstract_misleading": false,
        "fidelity_rationale": "<Reasoning or 'Accurate'>"
        }}
        """
        try:
            return self._execute(
                temperature=0.0, 
                system_msg=sys_prompt, 
                user_inputs={"input_data": f"Query: {topic}\nPaper Data: {paper_json_str}"}
            )
        except AtelierAIError as e:
            logger.warning(f"Paper extraction failed: {e}")
            return {"is_relevant": False, "ai_rank_score": 0, "answer": "Extraction Error"}

    def generate_copilot_synthesis(self, topic: str, valid_records: List[Any]) -> str:
        """
        Writes an objective literature review summarizing findings from multiple relevant papers.
        
        Args:
            topic (str): The user's original query.
            valid_records (List[Any]): A list of extracted paper records/dictionaries.
            
        Returns:
            str: Markdown-formatted synthesis enriched with interactive citation tooltips.
        """
        sys_prompt = """
        You are the Atelier Synthesizer, an expert at writing academic literature reviews.
        Your task is to read the provided paper extracts and write a highly structured, objective summary answering the user's topic.

        Rules:
        1. Base your answer ENTIRELY on the provided insights. Do not introduce outside knowledge.
        2. Always start with a 2-to-3 sentence introductory paragraph summarizing the broad consensus or main takeaway.
        3. Dynamically choose the best formatting for the body:
        - If the papers discuss distinct variables/causes, use a "Key Factors" Markdown table.
        - If the papers debate an issue, use a "Pros & Cons" list.
        - If the query asks for a definition, use thematic bullet points.
        4. You MUST cite the source of every claim using bracketed numbers corresponding to the paper index (e.g., [1]). 
        CRITICAL: If citing multiple papers, use separate brackets like [1][2]. DO NOT use comma-separated formats like [1, 2].
        5. Conclude with a brief 1-sentence wrap-up identifying gaps in the literature if applicable.
        """
        
        context = "".join([f"[{i+1}] {_get_val(r, 'title')} - {_get_val(r, 'answer')}\n" for i, r in enumerate(valid_records)])
        
        try:
            raw_md = self._execute(
                temperature=0.1, 
                system_msg=sys_prompt, 
                user_inputs={"input_data": f"Topic: {topic}\nContext:\n{context}"}, 
                is_json=False
            )
            return _enrich_citations(raw_md, valid_records)
        except AtelierAIError:
            return "<p>Failed to generate synthesis due to an AI processing error. Please try again.</p>"

    def followup_chat(self, query: str, current_topic: str, processed_records: List[Any]) -> dict:
        """
        Intent Router: Evaluates if a follow-up requires new external documents or 
        if it can be answered entirely within the current context scope.
        
        Args:
            query (str): The user's new question.
            current_topic (str): The overarching timeline topic.
            processed_records (List[Any]): Papers currently loaded in the feed view.
            
        Returns:
            dict: JSON containing 'intent' (SEARCH/CHAT) and an optimal 'standalone_query'.
        """
        sys_prompt = """You are an intelligent routing agent for an academic research engine.
            
            Task 1: Evaluate if the user's query can be confidently answered using ONLY the provided literature context.
            - If YES, route to 'CHAT'.
            - If NO (asking about a new demographic or new question), route to 'SEARCH'.
            
            Task 2: If SEARCH, combine the original topic and the follow-up into a single standalone search query.
            
            Return ONLY a valid JSON object matching this exact schema:
            {{"intent": "SEARCH" or "CHAT", "standalone_query": "merged query here or null"}}
            """
            
        context_preview = "".join([f"- {_get_val(r, 'title')}\n" for r in processed_records])
        user_input = {"input_data": f"Original Topic: {current_topic}\nContext:\n{context_preview}\nFollow-up: {query}"}
        
        try:
            result = self._execute(temperature=0.0, system_msg=sys_prompt, user_inputs=user_input)
            return result if isinstance(result, dict) else {"intent": "CHAT", "standalone_query": None}
        except Exception as e:
            logger.warning(f"Router fallback triggered: {e}")
            return {"intent": "CHAT", "standalone_query": None}

    @retry(stop=stop_after_attempt(3), wait=wait_exponential(multiplier=1, min=2, max=5), reraise=True)
    def chat_with_literature(self, chat_history: List[Dict[str, str]], context_records: List[Any]) -> str:
        """
        Context-aware Conversational RAG. Answers deep-dive questions based on the 
        currently loaded paper feed. Bypasses standard templates to safely ingest user strings.
        
        Args:
            chat_history (List[Dict]): Historical role/content pairings.
            context_records (List[Any]): Papers currently loaded in the feed view.
            
        Returns:
            str: AI response enriched with HTML citation tooltips.
        """
        llm = self._get_llm(temperature=0.3)
        context_str = "".join([f"[{i+1}] {_get_val(r, 'title')}\n{_get_val(r, 'abstract')}\n" for i, r in enumerate(context_records)])
        
        sys_prompt = f"""
        You are Atelier's specialized Academic Research Assistant.
        Your task is to answer the user's follow-up questions by conducting a "deep dive" into the provided literature context.

        Rules:
        1. CLOSED-BOOK: Your only source of truth is the provided Context. If the context does not contain the answer, you must explicitly state: "The provided literature does not contain information to answer this."
        2. Maintain an objective, academic tone. Avoid hyperbole.
        3. You MUST cite your claims using the bracketed numbers from the context headers (e.g., [1]).
        CRITICAL: If citing multiple papers, use separate brackets like [1][2]. DO NOT use comma-separated formats like [1, 2].

        Context:
        {context_str}
        """

        messages = [SystemMessage(content=sys_prompt)]
        
        # Keep only the last 6 messages to preserve token window
        for msg in chat_history[-6:]:
            if msg["role"] == "user":
                messages.append(HumanMessage(content=msg["content"]))
            else:
                messages.append(AIMessage(content=msg["content"]))
            
        try:
            raw_response = llm.invoke(messages).content
            return _enrich_citations(raw_response, context_records)
        except Exception as e:
            logger.error(f"Chat failed: {e}")
            return "I encountered an error connecting to the AI. Please try asking your question again."